# Generated by Django 4.2.5 on 2023-09-21 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="id",
        ),
        migrations.AddField(
            model_name="person",
            name="person_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
