# Generated by Django 4.2.5 on 2023-09-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0004_alter_person_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
