# Generated by Django 4.2.5 on 2023-09-22 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0005_alter_person_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
