# Generated by Django 4.2.5 on 2023-09-22 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0006_alter_person_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="date",
            new_name="created_at",
        ),
    ]
