# Generated by Django 4.2.5 on 2023-09-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0007_rename_date_person_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateField(),
        ),
    ]
