# Generated by Django 4.2.5 on 2023-09-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_management", "0004_remove_group_id_alter_group_created_at_and_more"),
        ("user_management", "0008_alter_person_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="groups",
            field=models.ManyToManyField(
                related_name="members", to="group_management.group"
            ),
        ),
    ]
