# Generated by Django 4.2.5 on 2023-09-26 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0009_person_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="groups",
        ),
    ]
