# Generated by Django 4.2.5 on 2023-09-26 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0010_remove_person_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="updared_at",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 26, 15, 31, 59, 160016, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
