# Generated by Django 4.2.5 on 2023-09-28 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0011_person_updared_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="updared_at",
            new_name="updated_at",
        ),
    ]
