# Generated by Django 4.2.5 on 2023-10-25 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(default=None, max_length=200)),
                ('transaction_amount', models.FloatField()),
                ('transaction_date', models.DateField()),
            ],
        ),
    ]
