# Generated by Django 4.2.5 on 2023-10-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction_management', '0001_initial'),
        ('group_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='split_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='split_by_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='split_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='group_transactions', to='group_management.group'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='split_with',
            field=models.ManyToManyField(related_name='split_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
