# Generated by Django 4.2.5 on 2023-09-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0012_rename_updared_at_person_updated_at"),
        ("group_management", "0012_alter_group_created_by"),
        ("transaction_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trasaction",
            name="created_by",
        ),
        migrations.AddField(
            model_name="trasaction",
            name="split_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transactions",
                to="user_management.person",
            ),
        ),
        migrations.AddField(
            model_name="trasaction",
            name="splitee",
            field=models.ManyToManyField(
                related_name="splitee", to="user_management.person"
            ),
        ),
        migrations.AddField(
            model_name="trasaction",
            name="updated_at",
            field=models.DateField(default=None),
        ),
        migrations.RemoveField(
            model_name="trasaction",
            name="group",
        ),
        migrations.AddField(
            model_name="trasaction",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transactions",
                to="group_management.group",
            ),
        ),
    ]
