# Generated by Django 4.2.5 on 2023-09-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("group_management", "0012_alter_group_created_by"),
        ("user_management", "0012_rename_updared_at_person_updated_at"),
        (
            "transaction_management",
            "0002_remove_trasaction_created_by_trasaction_split_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trasaction",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transactions",
                to="group_management.group",
            ),
        ),
        migrations.AlterField(
            model_name="trasaction",
            name="split_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transactions",
                to="user_management.person",
            ),
        ),
        migrations.AlterField(
            model_name="trasaction",
            name="updated_at",
            field=models.DateField(),
        ),
    ]
