# Generated by Django 4.2.5 on 2023-09-28 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "transaction_management",
            "0003_alter_trasaction_group_alter_trasaction_split_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trasaction",
            name="transaction_id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
