# Generated by Django 4.2.5 on 2023-09-28 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction_management", "0004_alter_trasaction_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trasaction",
            name="splitee",
        ),
    ]
