# Generated by Django 4.2.5 on 2023-09-28 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "transaction_management",
            "0006_trasaction_splitee_alter_trasaction_group_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="trasaction",
            old_name="created_at",
            new_name="transaction_date",
        ),
        migrations.RemoveField(
            model_name="trasaction",
            name="updated_at",
        ),
    ]
