# Generated by Django 4.2.5 on 2023-09-28 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "transaction_management",
            "0007_rename_created_at_trasaction_transaction_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="trasaction",
            old_name="group",
            new_name="split_group_id",
        ),
        migrations.RenameField(
            model_name="trasaction",
            old_name="splitee",
            new_name="split_with",
        ),
    ]
