# Generated by Django 4.2.5 on 2023-09-28 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0012_rename_updared_at_person_updated_at"),
        ("group_management", "0012_alter_group_created_by"),
        (
            "transaction_management",
            "0008_rename_group_trasaction_split_group_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Trasaction",
            new_name="Transaction",
        ),
    ]
