# Generated by Django 4.2.5 on 2023-09-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.CharField(max_length=200)),
                ("group_name", models.CharField(max_length=200)),
                ("group_length", models.IntegerField(default=0)),
                ("created_by", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(verbose_name="date created")),
                ("updated_at", models.DateTimeField(verbose_name="date updated")),
            ],
        ),
    ]
