# Generated by Django 4.2.5 on 2023-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_length",
            field=models.IntegerField(default=1),
        ),
    ]
