# Generated by Django 4.2.5 on 2023-09-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_management", "0002_alter_group_group_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateField(verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="group",
            name="updated_at",
            field=models.DateField(verbose_name="date updated"),
        ),
    ]
