# Generated by Django 4.2.5 on 2023-09-26 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("group_management", "0003_alter_group_created_at_alter_group_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="id",
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="updated_at",
            field=models.DateField(),
        ),
    ]
