# Generated by Django 4.2.5 on 2023-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0010_remove_person_groups"),
        ("group_management", "0005_group_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="groups",
            field=models.ManyToManyField(
                related_name="members", to="user_management.person"
            ),
        ),
    ]
