# Generated by Django 4.2.5 on 2023-09-26 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group_management", "0007_alter_group_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="groups",
            new_name="members",
        ),
    ]
