# Generated by Django 4.2.5 on 2023-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0010_remove_person_groups"),
        ("group_management", "0009_alter_group_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="groups", to="user_management.person"
            ),
        ),
    ]
